export const columns = [
    {
        label: "Index",
        dataKey: "Index",
    },
    {
        label: "Name",
        dataKey: "Name",
    },
    {
        label: "Overall Rating",
        dataKey: "Overall_Rating",
    },
    {
        label: "Cuisine",
        dataKey: "Cuisine",
    },
    {
        label: "Rate for two",
        dataKey: "Rate_for_two",
    },
    {
        label: "City",
        dataKey: "City",
    },
    {
        label: "Review",
        dataKey: "Review",
    },
];

export const rows = [
    {
        Index: 0,
        Name: 'Oliver Brown',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Juices, Beverages, Waffle, Desserts, Ice Cream',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: "Been to this place 3-4 times. Prakash is always very sweet and accommodating. Plus always ask Vaibhav to make your shakes, they are perfect!!",
    },
    {
        Index: 1,
        Name: 'Oliver Brown',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Juices, Beverages, Waffle, Desserts, Ice Cream',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: "I recently visited Oliver Brown on a weekend for a cup of iced coffee, and I was thoroughly impressed. The ambiance was inviting, the seating comfortable, and the service top-notch. I had the pleasure of trying their iced coffee and dark hot chocolate, both of which were absolutely delicious. It's an excellent place overall, and I'm already looking forward to my next visit.",
    },
    {
        Index: 2,
        Name: 'Crush Coffee',
        Overall_Rating: 3,
        Cuisine: 'Cafe, Shake, Beverages, Desserts',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Very watery and thin shake.',
    },
    {
        Index: 3,
        Name: 'The Mohalla',
        Overall_Rating: 3.8,
        Cuisine: 'Café',
        Rate_for_two: 550,
        City: 'Ahmedabad',
        Review: 'It was not a cheese burst pizza... only cheese was on the top... not happy with the pizza sent made today.',
    },
    {
        Index: 4,
        Name: 'The Mohalla',
        Overall_Rating: 3.8,
        Cuisine: 'Cafe',
        Rate_for_two: 550,
        City: 'Ahmedabad',
        Review: 'Yummy....test burger is the best I love üíó this Berger. And fry is also missing üòÇ. Love ‚ù§Ô∏è you ........',
    },
    {
        Index: 5,
        Name: 'The Shaka Café',
        Overall_Rating: 4.3,
        Cuisine: 'North Indian, Pizza, Asian, Chinese, Cafe, Desserts, Beverages',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: 'Food was not spicy, which I was told to the restaurant on call and instructions.',
    },
    {
        Index: 6,
        Name: 'The Shaka Cafe',
        Overall_Rating: 4.3,
        Cuisine: 'North Indian, Pizza, Asian, Chinese, Cafe, Desserts, Beverages',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: 'Punjabi Thali is great. The taste was good and paratha was the star. The reason simple being provided instead of maida made Naan. So overall mindful serving to the customer and liked it.',
    },
    {
        Index: 7,
        Name: 'Hobnob Bistro',
        Overall_Rating: 3.7,
        Cuisine: 'North Indian, Cafe, Italian, Chinese, Desserts, Shake, Beverages',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: "The owner didn't let us sit in the AC though it was not at all reserved. We already had booked our table priorly then also he didn't give us the AC table to sit. He said that you should call us and book the AC table but no one ever picks the call at all.",
    },
    {
        Index: 8,
        Name: 'Mleko',
        Overall_Rating: 4.8,
        Cuisine: 'Cafe, Coffee, Bakery, Fast Food, Continental, Desserts, Beverages',
        Rate_for_two: 800,
        City: 'Ahmedabad',
        Review: 'Both coffees were spilled and the box of pasta was opened up with coffee in the pasta. We need the money back since the items were completely inedible. I wish I had negative stars.',
    },
    {
        Index: 9,
        Name: 'Kaffee - Mast Hai',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Pasta, Burger, Sandwich, Pizza, Wraps, Desserts, Beverages',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: "Washroom was not available. Had to use mall's security guard's washroom.",
    },
    {
        Index: 10,
        Name: 'Kaffee - Mast Hai',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Pasta, Burger, Sandwich, Pizza, Wraps, Desserts, Beverages',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: 'Waiters denied to serve the food.',
    },
    {
        Index: 11,
        Name: 'Kaffee - Mast Hai',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Pasta, Burger, Sandwich, Pizza, Wraps, Desserts, Beverages',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: 'not tasty today food',
    },
    {
        Index: 12,
        Name: 'Unlocked',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Fast Food, North Indian, Chinese, Desserts, Beverages, Italian',
        Rate_for_two: 1200,
        City: 'Ahmedabad',
        Review: 'potion size has reduced. quality of food is nice',
    },
    {
        Index: 13,
        Name: 'Caffix - The Tech Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Sandwich, Italian, Continental, Oriental, Salad, Desserts, Beverages',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: 'Zomato shows 15% off on dining bill and the owner says we can offer 15% discount only if the bill is a minimum of Rs. 1000. Zomato doesn\'t mention any such thing but these guys have their own rules. What a joke! Customer banne se pehle hi customer tut gaya.',
    },
    {
        Index: 14,
        Name: 'Caffix - The Tech Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Sandwich, Italian, Continental, Oriental, Salad, Desserts, Beverages',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: 'I received the delivery 15 minutes late, but it was worthüëçüëç',
    },
    {
        Index: 15,
        Name: 'Novelchef Cafe & Lounge',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Continental, Italian, Fast Food, Desserts, Beverages',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Tried a new quiet amazing place after quite some time and I,Äôll just say that I LOVED IT. Food, ambience and Anurag Pandey ji ki service aaayyhayyyhayyhayyy ü´∂üèª maza aa gaya üéâ',
    },
    {
        Index: 16,
        Name: 'Gamysticafe',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Beverages, Sandwich, Fast Food, Mexican, Chinese, Desserts, Shake',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'New concept of the cafe is quiet appealing that,Äôs game+foodLike the food here Have visited this cafe several times Previously it used to b so much chaotic which was a minus point but now I think that is managed Every item v ordered here so far is yummy so far no complaints They have recently made changes in menu which I think is trouble becoz very short menu by far but I would appreciate that they manage to make a whole wheat paratha in place of all purpose flour in their combos Secondly their Mexican Buddha bowl is so yum',
    },
    {
        Index: 17,
        Name: 'Gamysticafe',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Beverages, Sandwich, Fast Food, Mexican, Chinese, Desserts, Shake',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'okay-ish cafe, only go here if you\'re interest in video games and have a large friend group. I had kitkat shake, it turned out, again, okay.',
    },
    {
        Index: 18,
        Name: 'Xero Degrees',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Italian, Continental, Mexican, Fast Food, Beverages',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Drooling Food üòãü§§Most #Instagrammable Cafe of #Ahmedabad@xerodegrees_india What I have tried Here, úÖCheesy margarita pizzaMango mint coolerCheese balls friesF.R.I.E.N.D sliders Nutella oreo shakeDo visit this Place with your friends & Family !',
    },
    {
        Index: 19,
        Name: 'Xero Degrees',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Italian, Continental, Mexican, Fast Food, Beverages',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Favourite place for hangout with friends nearby SBRLove there Fries, Mocktail, Äôs & shakes Best 6 items to try out at here üíå- Peri Peri Cheesy Fries üíú- Makhni Paneer Heart Shape Pizza üíô- American Cheese Burger üñ§- Friends Sliders üíõ- Kwi Coolers üíö- Choco Brownie Freak shake ü§éXero Degrees is a casual fast food cafe serving American cuisine üíôUltimate destination for finger-licking food ‚úÖ',
    },
    {
        Index: 20,
        Name: 'Xero Degrees',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Italian, Continental, Mexican, Fast Food, Beverages',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'bakwas',
    },
    {
        Index: 21,
        Name: 'Xero Degrees',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Italian, Continental, Mexican, Fast Food, Beverages',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'The staff is rude, they behave as if they are obliging on us & providing service & food for free. We ordered alfredo pasta, jain margarita pizza & fried wonton. Pasta & wonton were good but pizza was way too sweet. Upon confronting the staff, their response was slow & made faces. They responded that we use ready-made sauces so it would taste sweet only in a rude way & didn\'t mention it at the time of placing the order. We do understand that servers are not responsible for the taste of food but they should respond properly.',
    },
    {
        Index: 22,
        Name: 'Cuppuccino',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, North Indian, Chinese, Mexican, Pizza, Pasta, Fast Food, Beverages',
        Rate_for_two: 850,
        City: 'Ahmedabad',
        Review: 'Very bad taste. I hate it...it was not baked properly.',
    },
    {
        Index: 23,
        Name: 'Core The Coffee Shop @ Lithosphere',
        Overall_Rating: 3.8,
        Cuisine: 'Pizza, Burger, Pasta, Oriental, Cafe, Shake, Beverages',
        Rate_for_two: 2000,
        City: 'Ahmedabad',
        Review: 'There were two thick strands of hair in my sandwich.',
    },
    {
        Index: 24,
        Name: 'Core The Coffee Shop @ Lithosphere',
        Overall_Rating: 3.8,
        Cuisine: 'Pizza, Burger, Pasta, Oriental, Cafe, Shake, Beverages',
        Rate_for_two: 2000,
        City: 'Ahmedabad',
        Review: 'Too late.',
    },
    {
        Index: 25,
        Name: 'Fyro',
        Overall_Rating: 3,
        Cuisine: 'Cafe, Coffee, Shake, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Worst service, the staff doesn, Äôt hear your order well and then doesn, Äôt even have the courtesy to talk to their customer well and get their order replaced.üëéüèª',
    },
    {
        Index: 26,
        Name: 'I Love Sandwich House',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Tea, Beverages, Sandwich, Coffee',
        Rate_for_two: 1100,
        City: 'Ahmedabad',
        Review: 'Very bad salad. Stale refried chicken. Had not expected such bad quality food from this place. Tasted and then ordered something else from upper crust.',
    },
    {
        Index: 27,
        Name: 'I Love Sandwich House',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Tea, Beverages, Sandwich, Coffee',
        Rate_for_two: 1100,
        City: 'Ahmedabad',
        Review: 'The rosti is undercooked and there is no spoon or fork. How to eat it in an office.',
    },
    {
        Index: 28,
        Name: 'I Love Sandwich House',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Tea, Beverages, Sandwich, Coffee',
        Rate_for_two: 1100,
        City: 'Ahmedabad',
        Review: 'More pieces of avocado and placement of pieces would be yummy.',
    },
    {
        Index: 29,
        Name: 'I Love Sandwich House',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Tea, Beverages, Sandwich, Coffee',
        Rate_for_two: 1100,
        City: 'Ahmedabad',
        Review: 'Bad taste.',
    },
    {
        Index: 30,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 4.4,
        Cuisine: 'Cafe, Sandwich, Pizza, Fast Food, Shake, Ice Cream, Coffee, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Great delivery & quality.',
    },
    {
        Index: 31,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 4.4,
        Cuisine: 'Cafe, Sandwich, Pizza, Fast Food, Shake, Ice Cream, Coffee, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Little overpriced may be due to Zomato other than that it\'s good.',
    },
    {
        Index: 32,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 4.4,
        Cuisine: 'Cafe, Sandwich, Pizza, Fast Food, Shake, Ice Cream, Coffee, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Really poor food quality.... totally waste of money. I\'ll never suggest this to anyone.',
    },
    {
        Index: 33,
        Name: 'Big Blue Bistro',
        Overall_Rating: '-',
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Pizza, Fast Food, Chinese, North Indian',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: 'It wasn\'t kathi roll at all .. it was Frankie.',
    },
    {
        Index: 34,
        Name: 'Silver Fork Cafe & Restaurant',
        Overall_Rating: '-',
        Cuisine: 'North Indian, Chinese, Continental, Italian, Mexican, Cafe, Beverages',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'I had an amazing experience at Silver Fork! The hotel\'s 5-star service truly exceeded my expectations. The dinner was outstanding, and the food was delicious - every dish was a culinary delight. I recommend Silver Fork for anyone looking for good food.',
    },
    {
        Index: 35,
        Name: 'Silver Fork Cafe & Restaurant',
        Overall_Rating: '-',
        Cuisine: 'North Indian, Chinese, Continental, Italian, Mexican, Cafe, Beverages',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'Food is very good. Ambience is good. No waiting period. Enough space to enjoy, specially suitable for Birthday party, Marriage Anniversary party, Engagement party, etc.',
    },
    {
        Index: 36,
        Name: 'Lil\' Heaven Cafe',
        Overall_Rating: 3.5,
        Cuisine: 'Cafe, North Indian, Italian, Sandwich, Beverages, Shake',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Pasta was a little too spicy. Please make less spicy food next time.',
    },
    {
        Index: 37,
        Name: 'Lil\' Heaven Cafe',
        Overall_Rating: 3.5,
        Cuisine: 'Cafe, North Indian, Italian, Sandwich, Beverages, Shake',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Poor. I ordered jain & they delivered with onions. I used to try new things that, Äôs why I ordered but disappointed.',
    },
    {
        Index: 38,
        Name: 'Wagh Bakri Tea Lounge',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Beverages, Fast Food, Desserts, Tea',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: 'Very nice packing and food.',
    },
    {
        Index: 39,
        Name: 'Wagh Bakri Tea Lounge',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Beverages, Fast Food, Desserts, Tea',
        Rate_for_two: 1000,
        City: 'Ahmedabad',
        Review: 'Taking of way of this guy very bad to the Zomato customer.',
    },
    {
        Index: 40,
        Name: 'Rasa Restro Cafe',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, North Indian, Italian, Mexican, Thai, Biryani, Desserts, Beverages',
        Rate_for_two: 1100,
        City: 'Ahmedabad',
        Review: 'Add more creamy gravy in pasto pasta. It\'s only pasta gravy; there are not enough.',
    },
    {
        Index: 41,
        Name: 'Indie Brewed Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Very bad iced Americano. Don, Äôt order from here.',
    },
    {
        Index: 42,
        Name: 'Indie Brewed Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Ordered from here thrice. I love what they offer. Price is very reasonable. They have shifted from Sindhu Bhavan Road to now opposite Alpha Mall. Order without a second thought.',
    },
    {
        Index: 43,
        Name: 'Indie Brewed Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'There is no ice in peach iced tea; in fact, it is not even cold.',
    },
    {
        Index: 44,
        Name: 'Aarambh Cafe',
        Overall_Rating: '-',
        Cuisine: 'Cafe, Coffee, South Indian, Street Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Nestled within the CEE campus in the Thaltej area of Ahmedabad, Café Aarambh offers a tranquil and serene ambience, providing a much-needed respite from the hustle and bustle of the city. While this café remains relatively unknown to many city dwellers, its peaceful atmosphere makes it a hidden gem worth discovering. However, when it comes to the culinary aspect, Café Aarambh falls short of expectations. The food offerings, unfortunately, do not match the serene ambience. The taste of the dishes is rather average, leaving much to be desired, especially considering the price one pays. The limited food options available might disappoint those looking for a diverse range of choices.',
    },
    {
        Index: 45,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Bakery, Waffle, Desserts, Beverages',
        Rate_for_two: 850,
        City: 'Ahmedabad',
        Review: 'Extreme oily, Veg puff was not at all fresh.',
    },
    {
        Index: 46,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Bakery, Waffle, Desserts, Beverages',
        Rate_for_two: 850,
        City: 'Ahmedabad',
        Review: 'The cake was stale, and the box\'s smell was coming.',
    },
    {
        Index: 47,
        Name: 'Oven The Bakery & Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Bakery, Waffle, Desserts, Beverages',
        Rate_for_two: 850,
        City: 'Ahmedabad',
        Review: 'It\'s a good place and I can vouch for their cheesecakes, but they cheat you. First of all, their dine-in price for cheesecake is 200, and on Zomato, they show 300. I have Zomato gold, and they would refuse me to pay through it by saying the Zomato 20% discount is only on the menu. But when you see their dining page, the first photo they have is of a cheesecake! Hypocrisy? I love their cheesecakes, but I don\'t like cheaters, so I\'d not go there again!',
    },
    {
        Index: 48,
        Name: 'Sphere Lounge - Hotel Ramada',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, North Indian, Chinese, Fast Food, Italian, Street Food, Sandwich, Panini',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Must visit.',
    },
    {
        Index: 49,
        Name: 'Sphere Lounge - Hotel Ramada',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, North Indian, Chinese, Fast Food, Italian, Street Food, Sandwich, Panini',
        Rate_for_two: 950,
        City: 'Ahmedabad',
        Review: 'Very very expensive & Agli oily pasta were not good at all. Portion size was very small. I highly do not recommend ordering from this place.',
    },
    {
        Index: 50,
        Name: 'Smash Cafe',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Fast Food, North Indian, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Excellent food. Menu is extensive and seasonal to a particularly high standard. Highly recommended.',
    },
    {
        Index: 51,
        Name: 'Brewers - The Coffee Bar',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Italian, North Indian, Mexican, Street Food, Salad, Beverages',
        Rate_for_two: 350,
        City: 'Ahmedabad',
        Review: 'Half of the coffee was spilled in the bag.',
    },
    {
        Index: 52,
        Name: 'Brewer Cafe & Restro',
        Overall_Rating: 3.1,
        Cuisine: 'Cafe, Pizza, Burger, Sandwich, Fast Food, Desserts, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Due to unavailability, my order was replaced with a burger which was not also good. Aloo tikki burger\'s bun is grilled/heated on a pan with ghee, and as per the taste, tikki felt like a frozen tikki and not the proper amount of sauces.',
    },
    {
        Index: 53,
        Name: 'Brewer Cafe & Restro',
        Overall_Rating: 3.1,
        Cuisine: 'Cafe, Pizza, Burger, Sandwich, Fast Food, Desserts, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Extremely less quantity according to the price, one person doing cooking, serving everything, thus too long waiting time.',
    },
    {
        Index: 54,
        Name: 'Brewer Cafe & Restro',
        Overall_Rating: 3.1,
        Cuisine: 'Cafe, Pizza, Burger, Sandwich, Fast Food, Desserts, Beverages',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Worst.',
    },
    {
        Index: 55,
        Name: 'Cafe Catchers',
        Overall_Rating: 3.3,
        Cuisine: 'Cafe, Shake, Beverages, Chinese, Italian, Mexican, Fast Food, North Indian',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'Won, Äôt order from here again. Regret.',
    },
    {
        Index: 56,
        Name: 'Cafe Catchers',
        Overall_Rating: 3.3,
        Cuisine: 'Cafe, Shake, Beverages, Chinese, Italian, Mexican, Fast Food, North Indian',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'Recently visited this newly opened place near Vastrapur to try their food. I had tried their special Mocktail, Maxican sizzler, stuffed mushroom and sizzling hot brownie. Food was delicious and freshly made. They have some discount and BOGo offers going on for January month. Must check and take benefits of it.',
    },
    {
        Index: 57,
        Name: 'Cafe Catchers',
        Overall_Rating: 3.3,
        Cuisine: 'Cafe, Shake, Beverages, Chinese, Italian, Mexican, Fast Food, North Indian',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'Best food!!! Thai was excellent as well as Punjabi!! A must-visit place for foodies!!! Nice and cozy place to sit with friends and family!!',
    },
    {
        Index: 58,
        Name: 'Cafe Catchers',
        Overall_Rating: 3.3,
        Cuisine: 'Cafe, Shake, Beverages, Chinese, Italian, Mexican, Fast Food, North Indian',
        Rate_for_two: 900,
        City: 'Ahmedabad',
        Review: 'A place to visit for food lovers in Ahmedabad. Such an appealing vibe the place had with delicious food by the side. They had one of the best North Indian food I had. Also, they have a wide range of cuisines available along with unique starters from Indian to Italian and Mexican cuisine. Do visit this place with your friends and family. My recommendation - Thai curry with herb rice, Cheese balls.',
    },
    {
        Index: 59,
        Name: "Shambhu's Coffee Bar",
        Overall_Rating: 3.3,
        Cuisine: 'Cafe, Shake, Beverages, Sandwich, Pizza, Fast Food, Desserts',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: "I went here for the second time with my husband; have ordered 'Dark Fantasy' and 'Brownie with Coffee' thick shakes. Both were good in taste - not amazing but regular in taste. The ambiance is also average - they have indoor as well as outdoor seating which is not much maintained. Even their Gpay was not working which was shocking and a downside.",
    },
    {
        Index: 60,
        Name: 'Vince Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Fast Food, Shake, Sandwich, Chinese',
        Rate_for_two: 450,
        City: 'Ahmedabad',
        Review: 'Good vibes in this cafe. Liked food quality. Beverages are too good and worth trying. Open cafe with good music and sometimes events.',
    },
    {
        Index: 61,
        Name: 'Vince Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Fast Food, Shake, Sandwich, Chinese',
        Rate_for_two: 450,
        City: 'Ahmedabad',
        Review: 'Avoid visiting this place. They\'ve been degrading with time. Food is creep, cringe. Just hyped somehow, totally avoid.',
    },
    {
        Index: 62,
        Name: 'Vince Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Fast Food, Shake, Sandwich, Chinese',
        Rate_for_two: 450,
        City: 'Ahmedabad',
        Review: 'Super friendly place with the best interior design and spacious enough to accommodate many at a time. Love the vibe it creates. Amazing items on the menu, best for nightlife in Ahmedabad.',
    },
    {
        Index: 63,
        Name: 'Cafe Selfie',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Shake, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Very small.',
    },
    {
        Index: 64,
        Name: 'Cafe Selfie',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Shake, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Good and Fresh staff members.',
    },
    {
        Index: 65,
        Name: 'Cafe Selfie',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Shake, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Nice place for food, and specially Location is nice and all shakes are awesome. Food is superb, will inform everyone to visit this place once.',
    },
    {
        Index: 66,
        Name: 'Chai Hai Na',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, Fast Food, Street Food, Beverages',
        Rate_for_two: 550,
        City: 'Ahmedabad',
        Review: "I don't know, but the original taste of badam chai is missing out since the last 2 days.... not sure what's wrong.",
    },
    {
        Index: 67,
        Name: 'Chai Hai Na',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, Fast Food, Street Food, Beverages',
        Rate_for_two: 550,
        City: 'Ahmedabad',
        Review: 'Badam shake is not good, not bad. Its taste must be improved.',
    },
    {
        Index: 68,
        Name: 'Busy Beans',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Beverages, Fast Food',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Pure coffee beans test and delicious... Good quality and packaging... Must try Blueberry Oreo Shake... And if Coffee lover than order Hazelnut cold coffee....',
    },
    {
        Index: 69,
        Name: '58 Cafe House',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Sugarless coffee and not sent with sugar totally wasted of money.',
    },
    {
        Index: 70,
        Name: '58 Cafe House',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Nice food.',
    },
    {
        Index: 71,
        Name: '58 Cafe House',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Worst chess used... it looks like we eat aata.',
    },
    {
        Index: 72,
        Name: 'Drunch',
        Overall_Rating: 3.5,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Pasta, Fast Food, Momos, Chinese',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'So they were refusing to accept payment through Zomato. Our bill value was 710 rupees, but the cafe owner saying that bill value should be 2000 or more for making payment through Zomato. Is this really a condition? This is not right at all.',
    },
    {
        Index: 73,
        Name: 'Drunch',
        Overall_Rating: 3.5,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Pasta, Fast Food, Momos, Chinese',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'A perfect open-air cafe in Ahmedabad. Live IPL screening every day. They have refreshing mocktails. I tried their mocktails, pizza, pasta, and bowl. Food was delicious and quality is also amazing. They have different sitting arrangements. A perfect place for planning a date or hangout with your friends.',
    },
    {
        Index: 74,
        Name: 'Cafe Cos',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Tea, Sandwich, Burger, Salad, Healthy Food, Beverages',
        Rate_for_two: 750,
        City: 'Ahmedabad',
        Review: 'Coffee was very watery and tasteless.',
    },
    {
        Index: 75,
        Name: 'Cafe Cos',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Tea, Sandwich, Burger, Salad, Healthy Food, Beverages',
        Rate_for_two: 750,
        City: 'Ahmedabad',
        Review: "If you're searching for a cafe that offers delicious, healthy alternatives to traditional pizza and pasta, look no further. I recently had the pleasure of visiting a healthy cafe that prides itself on using multigrain and whole wheat ingredients in their pizza and pasta dishes. I must say, I was thoroughly impressed with both the quality of the food and the commitment to healthier options. Here's my detailed review: Ambiance: The cafe had a cozy and inviting atmosphere, with a modern yet warm decor. The use of natural materials and earthy colors created a pleasant dining environment. The seating arrangements were comfortable, and the staff was friendly and attentive, making for an...",
    },
    {
        Index: 76,
        Name: 'Cafe Cos',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Tea, Sandwich, Burger, Salad, Healthy Food, Beverages',
        Rate_for_two: 750,
        City: 'Ahmedabad',
        Review: 'I had broccoli soup previously from the same restaurant, but today taste was totally different. It has more salt and pepper, and sometimes it tastes too salty and due to too much black pepper, it made spicy.',
    },
    {
        Index: 77,
        Name: 'Creamoholic Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Pizza, Burger, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Superb quality and freshly made.',
    },
    {
        Index: 78,
        Name: 'Creamoholic Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Pizza, Burger, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Superb experience. Better than any Cafe. The best for shakes and cold coffee. I tried dine in also and food and ambiance were unmatched. I recommend cold coffee shake and peri-peri fries. You can also taste pizza sandwich and burger average to the best taste.',
    },
    {
        Index: 79,
        Name: 'Creamoholic Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Pizza, Burger, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Garlic bread perfection. The Garlic Bread was a wonderful addition to my meal. The delivery was quick and the bread arrived fresh and aromatic.',
    },
    {
        Index: 80,
        Name: 'Creamoholic Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Pizza, Burger, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Hub Chilli Burger fiery treat for my taste buds. The delivery was quick and the burger was well-packed. The spicy patty along with the fresh lettuce created a perfect balance of flavors.',
    },
    {
        Index: 81,
        Name: "Shambhu's Cafe",
        Overall_Rating: null,
        Cuisine: 'Cafe, Fast Food',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: "Way taste was different as compared to Prahladnagar garden cafe Shambhus. Most bogus literally iced crush was coming n last chocolate topping was also too bad as if it was older one.",
    },
    {
        Index: 82,
        Name: "Shiva's Coffee Bar",
        Overall_Rating: null,
        Cuisine: 'Cafe, Mexican, Pizza, South Indian, Chinese, Fast Food, Beverages, Coffee',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Wrong food item delivered.',
    },
    {
        Index: 83,
        Name: "Shiva's Coffee Bar",
        Overall_Rating: null,
        Cuisine: 'Cafe, Mexican, Pizza, South Indian, Chinese, Fast Food, Beverages, Coffee',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Nice, I loved it.',
    },
    {
        Index: 84,
        Name: "Shiva's Coffee Bar",
        Overall_Rating: null,
        Cuisine: 'Cafe, Mexican, Pizza, South Indian, Chinese, Fast Food, Beverages, Coffee',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Good.',
    },
    {
        Index: 85,
        Name: 'Food Costa',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Sandwich, Pizza, Burger, Fast Food, Shake, Beverages',
        Rate_for_two: 650,
        City: 'Ahmedabad',
        Review: 'Food and packing both were pathetic.',
    },
    {
        Index: 86,
        Name: 'Food Costa',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Sandwich, Pizza, Burger, Fast Food, Shake, Beverages',
        Rate_for_two: 650,
        City: 'Ahmedabad',
        Review: 'Not worth the cost. Taste was completely bland with 88% green capsicum 12% onion.',
    },
    {
        Index: 87,
        Name: 'Food Costa',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Sandwich, Pizza, Burger, Fast Food, Shake, Beverages',
        Rate_for_two: 650,
        City: 'Ahmedabad',
        Review: "Quality was very, very bad. I'll never order from this again.",
    },
    {
        Index: 88,
        Name: 'Cafe After Hours',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Italian, Fast Food, Chinese, North Indian',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'I said medium spicy with please but very spicy. What is the meaning of giving cooking instruction... really upsetting situation.',
    },
    {
        Index: 89,
        Name: 'Cafe After Hours',
        Overall_Rating: null,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Italian, Fast Food, Chinese, North Indian',
        Rate_for_two: 500,
        City: 'Ahmedabad',
        Review: 'Awesome food and packaging.',
    },
    {
        Index: 90,
        Name: 'Edr Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Italian, Fast Food, Beverages, Shake',
        Rate_for_two: 350,
        City: 'Ahmedabad',
        Review: "I went to have some food but that was a bit costly, then I asked for Jamun shots but the manager replied that it's seasonal. (Bhai jamun ki season to chal rahi hai) didn\'t argue and left.",
    },
    {
        Index: 91,
        Name: 'Edr Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Italian, Fast Food, Beverages, Shake',
        Rate_for_two: 350,
        City: 'Ahmedabad',
        Review: 'WORST CAFE OF AHMEDABAD FOR SURE!',
    },
    {
        Index: 92,
        Name: 'Tony Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Sandwich, Burger, Pizza, Fast Food, Chinese, Shake, Beverages',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Testy food new amazing food test.',
    },
    {
        Index: 93,
        Name: 'Tony Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Sandwich, Burger, Pizza, Fast Food, Chinese, Shake, Beverages',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Good.',
    },
    {
        Index: 94,
        Name: 'Tony Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Sandwich, Burger, Pizza, Fast Food, Chinese, Shake, Beverages',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'Best food and place so good with dance place and food test of Mumbai. Yummy best place in Naroda so yummy.',
    },
    {
        Index: 95,
        Name: 'Cafe Kyzo',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Coffee, Tea, Shake, Beverages, Sandwich, Burger, Fast Food',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'The burgers are juicy, crisp, authentic and tasty, something I had been searching for a while. Definitely a perfect combo with fresh mocktails and coffee. Loved it.',
    },
    {
        Index: 96,
        Name: 'The Avenue Cafe',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, Fast Food, Coffee, Beverages, Sandwich',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'Black plastic found in chhole... image attached.',
    },
    {
        Index: 97,
        Name: 'The Avenue Cafe',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, Fast Food, Coffee, Beverages, Sandwich',
        Rate_for_two: 600,
        City: 'Ahmedabad',
        Review: 'The best cafe in the town! The coffee is amazing and the atmosphere is so cozy. Highly recommend!',
    },
    {
        Index: 99,
        Name: 'Ares Cafe',
        Overall_Rating: null,
        Cuisine: 'Cafe, Fast Food, Sandwich, Pizza, Wraps, Chinese, Shake, Beverages',
        Rate_for_two: 700,
        City: 'Ahmedabad',
        Review: 'All the food spilled in the bag. Similar review is already given by another customer few days back. Does Zomato really care about feedback or is it just a formality?',
    },
    {
        Index: 100,
        Name: "Veronica's",
        Overall_Rating: 3.2,
        Cuisine: 'Cafe',
        Rate_for_two: 1500,
        City: 'Mumbai',
        Review: "I feel this place is overhyped because of Instagram. There is nothing special or different about this place. It's just like many other cafés/restaurants. The menu is very similar to many other places. The food choice is EXTREMELY POOR. THE BEVERAGE MENU HAS MORE OPTIONS THAN THE FOOD MENU. THE PLACE IS really small, and the seating system is really bad too; they made us sit on a two-person table when we were 3 of us and refused to give us a 4 person table, and we sat pretty uncomfortably. Also, the rates are very expensive just because of its location. The taste of food is also very basic and average. Usually, when a place is expensive and the taste of the food is good, a person won't...",
    },
    {
        Index: 101,
        Name: "Veronica's",
        Overall_Rating: 3.2,
        Cuisine: 'Cafe',
        Rate_for_two: 1500,
        City: 'Mumbai',
        Review: 'Visited this place with my family, the food was good but the staff very annoying. He kept talking rudely and loudly like he was doing us a favor by taking our order. He was later replaced by a normal polite guy, hence didn\'t complain. Guys please make a note of it!',
    },
    {
        Index: 102,
        Name: "Veronica's",
        Overall_Rating: 3.2,
        Cuisine: 'Cafe',
        Rate_for_two: 1500,
        City: 'Mumbai',
        Review: 'Busted cold brew it was a mess it was spoilt is what I mean from this review I love their food but this takes away from it.',
    },
    {
        Index: 103,
        Name: 'Pune Baking Company - JW Marriott Pune',
        Overall_Rating: 4.5,
        Cuisine: 'Cafe, Sandwich, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'Ordered their chocolate milkshake, chocolate frappe, and strawberry milkshake and was super dissatisfied & disappointed. Super sweet, not really cold and honestly much better can be done at home. Did not really expect that. Chocolate croissant and butter croissant were excellent though.',
    },
    {
        Index: 104,
        Name: 'Pune Baking Company - JW Marriott Pune',
        Overall_Rating: 4.5,
        Cuisine: 'Cafe, Sandwich, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: "Looked up for good bakeries around Pune and reached here. Ordered coffee, berry frappe, danish pastry. The coffee was good, don't remember the name of the brew. The berry frappe was worth 350 rs. And consisted of churned milk with vanilla ice cream and strawberry syrup with whipped cream on the top. I think regular shakes available in local joints taste better than this. It was uber sweet and had no 'berry' whatsoever. Poor attempt at such a renowned hotel! The danish pastry was another disappointment. Topped with what seemed like stale mango shrikhand and cubes of stale mango, it was another bad outcome. We asked to talk to the chef but was not ultimately able to. Would NOT...",
    },
    {
        Index: 105,
        Name: 'Pune Baking Company - JW Marriott Pune',
        Overall_Rating: 4.5,
        Cuisine: 'Cafe, Sandwich, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: "This place was one of our favorites once upon a time, but now it's become beyond pathetic. The BLT sandwich had one piece of bacon and one piece of mini tomato and that's it just bread. Last time we also faced the same issue with the quality despite complaining they haven't taken any action and argue with us that everything is right. We have been regular here for almost 12 years so it's really dreadful experience. We will now discontinue going to this place and pass on this to our family friends as well. Guys really sad to see this.",
    },
    {
        Index: 106,
        Name: 'The Ritz-Carlton Tea Lounge: The Ritz-Carlton',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Tea, Desserts',
        Rate_for_two: 2000,
        City: 'Pune',
        Review: "The tea lounge is on the ground floor itself open hall area, dress code is none but smart casuals work (boys get your shoes on, girls can go for heels or sandals!) One should definitely go for the tea buffet packages which costs 825+ tax (9%), For unlimited beverages we tried most of the teas on the menu (my personal fav being blue earl grey) and mocchiato coffee. The food is not unlimited though, it comes as shown in the photo, the top layer of finger sandwiches three types (2 pieces of each) we opted for all three nonveg sandwiches which were present on the menu, I skipped ham so they replaced it with a chicken sandwich luckily. The next two layers were sweet and savory, again one piece of...",
    },
    {
        Index: 107,
        Name: 'The Ritz-Carlton Tea Lounge: The Ritz-Carlton',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Tea, Desserts',
        Rate_for_two: 2000,
        City: 'Pune',
        Review: 'Coffee, midnight talks, peace, wonderful service, comfort and what all can one experience. Addiction gets rigid here and refusal to coffee is far gone.',
    },
    {
        Index: 108,
        Name: 'The Ritz-Carlton Tea Lounge: The Ritz-Carlton',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Tea, Desserts',
        Rate_for_two: 2000,
        City: 'Pune',
        Review: 'Yummmmm.',
    },
    {
        Index: 109,
        Name: 'The Ritz-Carlton Tea Lounge: The Ritz-Carlton',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Tea, Desserts',
        Rate_for_two: 2000,
        City: 'Pune',
        Review: 'Totally mesmerized by Ritz Carlton Tea Lounge Experience. We went on a weekday so it was less crowded. My husband opted for "Hi Tea" set buffet and I a la carte. I can sense the quality of food by its taste and aroma. They have a wide range of coffee, tea, and other cold beverages. Service was prompt and it was super neat & clean. I would love to visit again with my friends & family.',
    },
    {
        Index: 110,
        Name: 'The Ritz-Carlton Tea Lounge: The Ritz-Carlton',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Tea, Desserts',
        Rate_for_two: 2000,
        City: 'Pune',
        Review: 'Ordered a cake got a kheer.. disappointed. Please check the cake before dispatch and delivery guys should be extra careful with the cake.',
    },
    {
        Index: 111,
        Name: 'Le Coffee House',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'No ventilation or air conditioning, lemon soda tasted like laundry water, stale shrunken fries from God knows what era, cold coffee tasted like thinned out mala\'s chocolate syrup. Bread bash next to it is a far better option and serves fresh fries.',
    },
    {
        Index: 112,
        Name: 'Le Coffee House',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'Very few places in town who serve really good sandwich and coffee and Le Coffee House is one of them. Their thick coffee and Bombay grilled sandwich are to die for. Really loved it.',
    },
    {
        Index: 113,
        Name: 'Le Coffee House',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'Best Bombay Grilled Sandwich Ever! One must try it! Nice and beautiful ambiance! And staff was quite fast and polite!',
    },
    {
        Index: 114,
        Name: 'Le Flamington',
        Overall_Rating: 4.9,
        Cuisine: 'Cafe, European',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'The review is late but I had to put it out here visited the cafe in July with two of my friends. It was Sunday and quite empty; we had ordered signature ice dark which was amazing highly recommend cannot wait to be back just to have it again. The butter croissant was amazing fresh. We had the Bombay sandwich and chicken sandwich the portion the taste everything was on point fresh. We had black forest cake and the grey which was unbelievable best desserts I ever had. Then we took the hand-rolled Belgian and the one more chocolate which was freshly made for takeaway and it was amazing. Such a nice place cannot wait to be back.',
    },
    {
        Index: 115,
        Name: 'Le Flamington',
        Overall_Rating: 4.9,
        Cuisine: 'Cafe, European',
        Rate_for_two: 700,
        City: 'Pune',
        Review: "The place is on the main road, ahead of Toit. The ambiance is nice with light music. The decor is nice as well. Most tables are at a distance from each other. The menu is pretty decent. Service is good and food was really good. Ordered the Le sandwich which had ham and beef, I felt that had too much bread with 2 layers but was filling and went well with the side of masala fries which were really good. The MOC omelet was nice and fluffy with a good filling of mushroom, cheese, and olives and the sourdough. The cream cheese salad was the best thing we had called for. The leaves, mushroom, olives, and cream cheese went very well with the sourdough. For drinks, we called for drinking...",
    },
    {
        Index: 116,
        Name: 'Le Flamington',
        Overall_Rating: 4.9,
        Cuisine: 'Cafe, European',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'The place is small but looks nice. The food was good. Be careful while selecting from the Vegan options though. Desserts are a must-try!',
    },
    {
        Index: 117,
        Name: 'Ventana',
        Overall_Rating: null,
        Cuisine: 'New, North Indian, European, Continental, Asian, Fast Food, Cafe, Coffee, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'I visited Ventana for my birthday celebration and it could not have been any better. The food, ambiance, and hospitality were above our expectations. You should definitely try the Butter Garlic Prawns and the Pepper Chicken. This place is a must-visit if you are looking for a cozy environment.',
    },
    {
        Index: 118,
        Name: 'Ventana',
        Overall_Rating: null,
        Cuisine: 'New, North Indian, European, Continental, Asian, Fast Food, Cafe, Coffee, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'Do yourself a favor and visit this lovely restaurant when you are in Vimannagar. The service is unmatched. The staff truly cares about your experience. The food is absolutely amazing – everything we tasted melted in our mouths. Absolutely the best meal we had while in. Highly recommend!',
    },
    {
        Index: 119,
        Name: 'Ventana',
        Overall_Rating: null,
        Cuisine: 'New, North Indian, European, Continental, Asian, Fast Food, Cafe, Coffee, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'Do yourself a favor and visit this lovely restaurant when you are in Vimananagar. The service is unmatched. The staff truly cares about your experience. The food is absolutely amazing – everything we tasted melted in our mouths. Absolutely the best meal we had while in. Highly recommend!',
    },
    {
        Index: 120,
        Name: 'Ventana',
        Overall_Rating: null,
        Cuisine: 'New, North Indian, European, Continental, Asian, Fast Food, Cafe, Coffee, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'Excellent setup with a rooftop setting that is also covered. It\'s airy and with artificial and real plants all around. Regarding food, I had ordered cream of veg soup, Jalapeno poppers, Asian Garlic pepper sauce cottage cheese, paneer lababdar, pepper cottage cheese pizza, arabbiata pasta, Walnut brownie with ice cream. All were great and the portion size was also generous. Also ordered a frappe with caramel addition. This could have been a little thicker and was the least impressive item. Paneer lababdar and pizza were the star of the show. Simply lip-smacking. Also, it is a pocket-friendly restaurant without compromising on food quality.',
    },
    {
        Index: 121,
        Name: 'One O Eight Cafe',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Pizza, Continental, Italian, Bakery, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'The falafel is too dry...maybe because the delivery takes a little while. The outer crust was too hard and chewy and the inner portion was too dry. Hummus is okay but less in quantity. Little tweaks and it will be totally worth it. For now, it was a 3/5 sort of experience.',
    },
    {
        Index: 122,
        Name: 'One O Eight Cafe',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Pizza, Continental, Italian, Bakery, Beverages',
        Rate_for_two: 1200,
        City: 'Pune',
        Review: 'Extremely salty. Not edible.',
    },
    {
        Index: 123,
        Name: 'The Chocolate Room',
        Overall_Rating: 4.1,
        Cuisine: 'Cafe, Shake, Beverages, Waffle, Bakery, Desserts, Italian, Mexican',
        Rate_for_two: 850,
        City: 'Pune',
        Review: 'They don\'t even know how to pack the parcel and when we complain to them they say it\'s not their fault.',
    },
    {
        Index: 124,
        Name: 'Tanoshii Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Sandwich, Pasta, Fast Food',
        Rate_for_two: 900,
        City: 'Pune',
        Review: 'Came across this Hidden Gem recently! Tanoshii Cafe is a co-working space and a super aesthetically pleasing cafe. The charges are very affordable, starting from Rs100 and the beverages are on the house. I love the ambiance; it has a cute boho-themed decor. Tanoshii Cafe also has a conference room where you can have your meetings and conferences. The terrace is so beautifully made, it gives a homely feeling. You can work here for hours. They have a good menu to choose from; definitely try out the pasta. Lovely cafe with a beautiful peaceful vibe.',
    },
    {
        Index: 125,
        Name: 'Tanoshii Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Sandwich, Pasta, Fast Food',
        Rate_for_two: 900,
        City: 'Pune',
        Review: 'What if we had a cafe and a co-working space both in one place? This newest cafe plus co-working space opened on SB road Pune is the ultimate business and social gathering experience. Tanoshii means FUN in Japanese, and this co-working space is true to its name. It offers you a fun environment while working. They have a cozy co-working space with High-speed Wi-Fi, beverages are on the house. Charges start from just 100. They have a pretty huge conference room to set up meetings, seminars, events, and much more. They have a variety of options in food and beverages. And not to forget, the washrooms are so so pretty and clean! The interiors here are warm, comforting, and aesthetically...',
    },
    {
        Index: 126,
        Name: 'Tanoshii Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Sandwich, Pasta, Fast Food',
        Rate_for_two: 900,
        City: 'Pune',
        Review: 'Tanoshii Cafe Pune\'s Bustling Cafe Culture gets a new aesthetic cafe and coworking space- Tanoshii Cafe. This cafe located on Senapati Bapat Road offers you serene and comforting vibes. The ambiance is aesthetic, gorgeous, and artistic. Talking about this unique space, it has been thoughtfully curated and little details are specially taken care of. They also got many gram-worthy spots which are perfect for clicking pictures. It\'s a perfect place for events, group meetings (as they have a conference room as well) or casual hangouts with friends. You get an hour pass for 100, a day pass for 700 and a monthly pass for 5000, where you can work with high-speed internet...',
    },
    {
        Index: 127,
        Name: 'Tanoshii Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Sandwich, Pasta, Fast Food',
        Rate_for_two: 900,
        City: 'Pune',
        Review: 'Very peaceful and cozy atmosphere, the staff is very welcoming. The service was perfect, no delays, no complaints. Try their variety of croissants and cheesecakes. A very enthusiastic and calm co-working space!!',
    },
    {
        Index: 128,
        Name: 'Tanoshii Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Shake, Beverages, Sandwich, Pasta, Fast Food',
        Rate_for_two: 900,
        City: 'Pune',
        Review: 'Tanoshii is nested in the beautiful lanes of Model Colony which is a two-storied co-working and cafe space! A serene space where the aesthetics will feel like home and vibes that will keep you coming back! This time-based cafe has ample space to work from and chill with a beautiful terrace, conference room and so much more that you are to experience it yourself!',
    },
    {
        Index: 129,
        Name: 'One World - The Coffee Studio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Coffee, Tea, Salad, Fast Food, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'Best food quality. Best service by Shruti.',
    },
    {
        Index: 130,
        Name: 'One World - The Coffee Studio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Coffee, Tea, Salad, Fast Food, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'Very nice place really loved the service. Very helpful staff and yummy food. Highly recommend the Rose Kissed Latte and Sandwich.',
    },
    {
        Index: 131,
        Name: 'One World - The Coffee Studio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Coffee, Tea, Salad, Fast Food, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'This place is amazing! They offered the best coffee and showed the best attitude to its customers. I visited with my family; we had a great time also this place is perfect for studying and chilling out. It was very quiet, air-conditioned with very fast and unlimited internet connection.',
    },
    {
        Index: 132,
        Name: 'One World - The Coffee Studio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Coffee, Tea, Salad, Fast Food, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'A nice place to enjoy coffee and some tea cakes with friends. Open late night, this place has an amazing ambiance, good and polite staff, and some amazing coffee options. Must try - Chocolate Orange Cake.',
    },
    {
        Index: 133,
        Name: 'One World - The Coffee Studio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Coffee, Tea, Salad, Fast Food, Desserts',
        Rate_for_two: 1300,
        City: 'Pune',
        Review: 'The desserts we had were excellent and the coffee too. The ambiance is a pure class setup. Worth a visit.',
    },
    {
        Index: 134,
        Name: 'Back To Basics',
        Overall_Rating: 2.8,
        Cuisine: 'Cafe, Coffee, Beverages, Sandwich, Fast Food, Healthy Food, Desserts',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Food at its best! Ambiance at its best! Loved the cafe setup too. A must-visit place to try some different kind of food and dessert.',
    },
    {
        Index: 135,
        Name: 'Back To Basics',
        Overall_Rating: 2.8,
        Cuisine: 'Cafe, Coffee, Beverages, Sandwich, Fast Food, Healthy Food, Desserts',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Good and authentic food and dessert corner of Wadgaon Sheri; one can easily enjoy the place considering its location. But a must-go! I love it. Quantity also good too.',
    },
    {
        Index: 136,
        Name: 'Back To Basics',
        Overall_Rating: 2.8,
        Cuisine: 'Cafe, Coffee, Beverages, Sandwich, Fast Food, Healthy Food, Desserts',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Great cafe! Their breads are amazing in quality and quantity. You can really feel the goodness of whole wheat and ragi. My favorite place now. Great and polite staff. Keep up the great work, guys!',
    },
    {
        Index: 137,
        Name: 'Jamie\'s Pizzeria By Jamie Oliver',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Salad, Fast Food, Pizza, Italian, Desserts, Beverages',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Pizza is fine, the crispy seafood\'s quality isn\'t consistent, sometimes it\'s great, today not so much.',
    },
    {
        Index: 138,
        Name: 'Jamie\'s Pizzeria By Jamie Oliver',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Salad, Fast Food, Pizza, Italian, Desserts, Beverages',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Very good and tasty but due to traffic I guess the pizza was not warm.',
    },
    {
        Index: 139,
        Name: 'Jamie\'s Pizzeria By Jamie Oliver',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Salad, Fast Food, Pizza, Italian, Desserts, Beverages',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Worst delivery experience. The pizza is smashed and destroyed.',
    },
    {
        Index: 140,
        Name: 'Jamie\'s Pizzeria By Jamie Oliver',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Salad, Fast Food, Pizza, Italian, Desserts, Beverages',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'We ordered 3 items: fish fingers - really greasy, fish tasted old or frozen. I would not suggest any fried products as it seems like they\'re frozen and it ends up tasting really weird. Pepperoni pizza - nice crust, decent-tasting pizza, pretty standard, and I think any pizza might be a good choice as it seems to be their specialty. Lemon ginger beer - refreshing summery drink, heavier on the ginger flavor so if you don\'t like that then you might not enjoy it. Request to the restaurant - please improve your fish fingers; it was really disappointing :(',
    },
    {
        Index: 141,
        Name: 'IKOV Art Cafe Studio',
        Cuisine: 'Cafe, Sandwich, Desserts, Beverages',
        Rate_for_two: 300,
        City: 'Pune',
        Review: 'Loved the vibe of the place. Good place for hangout with friends and family. Quick bites available for munching.',
    },
    {
        Index: 142,
        Name: 'Cafe Nadora By Sneha',
        Overall_Rating: 'New',
        Cuisine: 'Cafe, Bakery, Fast Food, Sandwich, Coffee',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'It’s been twice that we visited Nadora and it has an excellent vibe to the place- Calm, serene and great place to have good conversations with some excellent quality food. The place is clean and classy and has decent enough space and good lighting. The location too is cozy. We’ve had the hot chocolate which is the best I’ve had! The Vietnamese coffee which is amazing, croissants are lovely and full, the sandwiches with the focaccia bread were bomb too. Will continue to visit Nadora, especially for the Hot chocolate. I am yet to try the other sweet items on the shelf as well.',
    },
    {
        Index: 143,
        Name: 'Cafe Nadora By Sneha',
        Overall_Rating: 'New',
        Cuisine: 'Cafe, Bakery, Fast Food, Sandwich, Coffee',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Everything was absolutely great, especially the Caprese Sandwich in a Croissant. But the Pickled Pear and Goat Cheese is an acquired taste probably, wasn\'t something I liked. It could definitely be someone else\'s cup of tea. Great food overall.',
    },
    {
        Index: 144,
        Name: 'Cafe Peter',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Tea, Beverages, Continental, Japanese, Sandwich, Fast Food, Desserts',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Get ramen without veg stock. I have mentioned that don\'t add mushrooms but they have added.',
    },
    {
        Index: 145,
        Name: 'Cafe Peter',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Tea, Beverages, Continental, Japanese, Sandwich, Fast Food, Desserts',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Received ramen without veg stock.',
    },
    {
        Index: 146,
        Name: 'The Burger Barn Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Shake, Beverages, Burger, American, Sandwich, Fast Food, Salad',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Very nice ambiance as it is a rooftop cafe, they have maintained the same taste and same quality in all outlets in Pune from the past several years. Barn veggie burger Mexican style - 3.5/5 Veg extreme burger - 4/5 Barn chilly cheese fries - 2.5/5',
    },
    {
        Index: 147,
        Name: 'The Burger Barn Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Shake, Beverages, Burger, American, Sandwich, Fast Food, Salad',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'My fav burger.',
    },
    {
        Index: 148,
        Name: 'The Burger Barn Cafe',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Shake, Beverages, Burger, American, Sandwich, Fast Food, Salad',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Portion size is good but taste and quality can be improved considering the price point.',
    },
    {
        Index: 149,
        Name: 'Hustle Snooker Cafe Bistro',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Sandwich, Pizza, Burger, Fast Food, Shake, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'The pizza was cold and not in good shape and the whole pizza is having a weird taste.',
    },
    {
        Index: 150,
        Name: 'Hustle Snooker Cafe Bistro',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Sandwich, Pizza, Burger, Fast Food, Shake, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Best cold coffee! üòç',
    },
    {
        Index: 151,
        Name: 'Brooster Coffeespot',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Tea, Sandwich, Salad, Pizza, Desserts',
        Rate_for_two: 1250,
        City: 'Pune',
        Review: 'Brooster is situated in Kalyani Nagar, is a beautiful cafe with great interiors + huge windows + and amazing food! üåßÔ∏è‚òïÔ∏è Coffee is a must if you are here! Must visit! üôåüèª',
    },
    {
        Index: 152,
        Name: 'Brooster Coffeespot',
        Overall_Rating: 3.7,
        Cuisine: 'Cafe, Coffee, Tea, Sandwich, Salad, Pizza, Desserts',
        Rate_for_two: 1250,
        City: 'Pune',
        Review: 'Very good ambiance and vibe. The menu is decent. The variety seems a little narrow spectrum in general but worked for me, maybe won\'t for someone with a lesser wide palate. The coffee was good. However, it didn\'t match half its look in terms of taste. I knew what I\'m ordering, I knew what the standard dish would have but the server on confirmation couldn\'t explain. He kept saying it will have cream whipped cream of some kind but it won\'t be cream also. Not how it works. You can\'t trust someone with your food when they don\'t know what it is. Breakfast dishes tasted decent. Avocado toast was borderline average. Shakshuka was 5/5 for sure. üíØ Tiramisu iced latte was a great iced coffee...read more',
    },
    {
        Index: 153,
        Name: 'K.K\'s Cafe',
        Cuisine: 'Sandwich, Fast Food, Street Food, Pizza, Burger, Tea, Coffee, Cafe',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Taste was not good.',
    },
    {
        Index: 154,
        Name: 'Aeka Coffee',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Fast Food',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Solo Espresso was a shot of pure energy! The intense flavor and rich crema were top-notch, and it was evident that the coffee beans were of high quality.',
    },
    {
        Index: 155,
        Name: 'Aeka Coffee',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Fast Food',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'My Americano coffee arrived piping hot and was a much-needed boost to start my day. The flavor was bold and robust, just how I like it. The delivery was quick and ensured I got my coffee fix right on time.',
    },
    {
        Index: 156,
        Name: 'Aeka Coffee',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Fast Food',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Paneer Wrap was a mouthwatering delight! The paneer was well-seasoned and combined perfectly with the fresh veggies and sauce.',
    },
    {
        Index: 157,
        Name: 'Aeka Coffee',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Fast Food',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Olive & Jalapeno Croissant was a perfect blend of savory and spicy flavors! The croissant was flaky and filled with delicious olives and jalapenos.',
    },
    {
        Index: 158,
        Name: 'Aeka Coffee',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Fast Food',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Mushroom Sandwich was a delightful surprise! The savory mushrooms and flavorful sauce made this sandwich stand out. It arrived promptly, and the taste exceeded my expectations.',
    },
    {
        Index: 159,
        Name: 'La Segreto Cafe And Resto',
        Cuisine: 'Cafe, Coffee, Burger, Pizza, Pasta, Italian, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'A must-visit place.',
    },
    {
        Index: 160,
        Name: 'La Segreto Cafe And Resto',
        Cuisine: 'Cafe, Coffee, Burger, Pizza, Pasta, Italian, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Loved the food and ambiance with the exotic touch of jazz music in the background. Must visit cafe, and it has co-working space as well.',
    },
    {
        Index: 161,
        Name: 'La Segreto Cafe And Resto',
        Cuisine: 'Cafe, Coffee, Burger, Pizza, Pasta, Italian, Fast Food, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'The quality of food is awesome and the taste of pizza is superb. Really appreciate customer satisfaction. Keep it up!',
    },
    {
        Index: 162,
        Name: 'Ambrosia Patisserie & Cafe - Ambrosia Resort & Spa',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Bakery, Beverages, Desserts',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Ambrosia is a really quiet and nice area, surrounded by lots of trees that make you feel like you\'re in the jungle. Nice location if you want to escape the bustle of the city. The food is top-notch. There is no compromising on food quality or quantity. Excellent vegetarian and non-vegetarian meal options, must visit place with friends and family!',
    },
    {
        Index: 163,
        Name: 'Ambrosia Patisserie & Cafe - Ambrosia Resort & Spa',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Bakery, Beverages, Desserts',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Loved their starters and veg Biryani.',
    },
    {
        Index: 164,
        Name: 'Ambrosia Patisserie & Cafe - Ambrosia Resort & Spa',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Bakery, Beverages, Desserts',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Enjoy this beautiful cuisine at this beautiful resort at Bavdhan, Pune. This place has spiritual vibes, and also this place is located in the heaven of nature like while having lunch you can hear the echo of peacock’s. They have excellent ambiance. Reasonable rates with good quality food. So do visit this resort.',
    },
    {
        Index: 165,
        Name: 'Ambrozia Cafe And Patisserie',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Bakery, Italian, Pizza, Sandwich, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'I love this place üíó. Great ambiance...Their Sinful Molten Chocolate with Ice-cream is a masterpiece, I\'m full yet I can\'t stop having itü§åü§åü§§ü§§',
    },
    {
        Index: 166,
        Name: 'Ambrozia Cafe And Patisserie',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Bakery, Italian, Pizza, Sandwich, Fast Food, Desserts, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Macarons were broken.',
    },
    {
        Index: 167,
        Name: 'Cafe Da Al Forno',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Fast Food, Pizza, Pasta, Sandwich, Beverages',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'It was okay, not as it has the rating. I think it is a fake rating, please guys don\'t buy from here.',
    },
    {
        Index: 168,
        Name: 'Cafe Fairytale',
        Overall_Rating: 'New',
        Cuisine: 'Cafe, Fast Food',
        Rate_for_two: 300,
        City: 'Pune',
        Review: 'The chef\'s special, Baked Mac & Cheese is exquisite.',
    },
    {
        Index: 169,
        Name: 'Cafe Fairytale',
        Overall_Rating: 'New',
        Cuisine: 'Cafe, Fast Food',
        Rate_for_two: 300,
        City: 'Pune',
        Review: 'Food and ambience were very nice.',
    },
    {
        Index: 170,
        Name: 'Daily Treats - The Westin Pune',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, Continental, Beverages, Desserts',
        Rate_for_two: 1800,
        City: 'Pune',
        Review: 'Sensational place. Our favorite of all the 5-star hotels, must-visit for all.',
    },
    {
        Index: 171,
        Name: 'BREWBURG',
        Overall_Rating: 'New',
        Cuisine: 'Cafe, Coffee, Fast Food, Burger, Beverages',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'Enjoyed the mealüòä',
    },
    {
        Index: 172,
        Name: 'Cocoa Patisserie and Bakery',
        Overall_Rating: 4.1,
        Cuisine: 'Bakery, Cafe, Desserts',
        Rate_for_two: 250,
        City: 'Pune',
        Review: 'Just Fine.',
    },
    {
        Index: 173,
        Name: 'Cocoa Patisserie and Bakery',
        Overall_Rating: 4.1,
        Cuisine: 'Bakery, Cafe, Desserts',
        Rate_for_two: 250,
        City: 'Pune',
        Review: 'Cupcakes had melted and fallen over sideways.',
    },
    {
        Index: 174,
        Name: 'Cocoa Patisserie and Bakery',
        Overall_Rating: 4.1,
        Cuisine: 'Bakery, Cafe, Desserts',
        Rate_for_two: 250,
        City: 'Pune',
        Review: 'Cake quality was awesome.. but delivered cake was not in good condition.. it was a mess .. kindly look into it.. what u can do for it.',
    },
    {
        Index: 175,
        Name: 'Cafe From The Tree',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Beverages, Desserts, Italian, Fast Food, Pasta, Pizza',
        Rate_for_two: 850,
        City: 'Pune',
        Review: 'Horrible portion size... this is what they serve for 240/- rupees... a slap on the face.',
    },
    {
        Index: 176,
        Name: 'Cafe From The Tree',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Beverages, Desserts, Italian, Fast Food, Pasta, Pizza',
        Rate_for_two: 850,
        City: 'Pune',
        Review: "Pizza came tangled and messy and it wasn't even cut into pieces.",
    },
    {
        Index: 177,
        Name: 'Cafe From The Tree',
        Overall_Rating: 4.3,
        Cuisine: 'Cafe, Beverages, Desserts, Italian, Fast Food, Pasta, Pizza',
        Rate_for_two: 850,
        City: 'Pune',
        Review: 'The pizza is not sliced.',
    },
    {
        Index: 178,
        Name: 'De Baillio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Bakery, Fast Food, Beverages, Desserts',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'I\'ve taken cakes & pastries from here many times. It is a better option than most cake shops in Baner. Good options and great taste.',
    },
    {
        Index: 179,
        Name: 'De Baillio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Bakery, Fast Food, Beverages, Desserts',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'I received a pastry instead of coffee.',
    },
    {
        Index: 180,
        Name: 'De Baillio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Bakery, Fast Food, Beverages, Desserts',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'Yummy.',
    },
    {
        Index: 181,
        Name: 'De Baillio',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Bakery, Fast Food, Beverages, Desserts',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'I am surprised that I had placed an order on the shop called De Baillio, whereas the cake got delivered from the shop called Bailey\'s.... Have you started to deliver from the shop of your choice rather than the customer\'s?',
    },
    {
        Index: 182,
        Name: 'Words & Sips Book Cafe',
        Overall_Rating: 3.2,
        Cuisine: 'Cafe, Fast Food, Chinese, Beverages',
        Rate_for_two: 550,
        City: 'Pune',
        Review: 'Food quality and taste are nice üòã prices are very much similar to other cafes on FC Road. The sitting here is different as they have sofas where you can sit. Ambience is pretty cool, and you will definitely find peace ‚úåÔ∏è. Free wifi available. They charge 100 rs per person as an entry fee which you can adjust in your bill.',
    },
    {
        Index: 183,
        Name: 'Salisbury Swiss Cafe',
        Overall_Rating: 3.1,
        Cuisine: 'Cafe, Sandwich, Pizza, Fast Food, Shake, Coffee, Beverages',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Worst place ever to visit. Told us to wait for 10 minutes and made us wait for 45 minutes and still no table was available. Horrible management and worst service one could possibly imagine.',
    },
    {
        Index: 184,
        Name: 'Salisbury Swiss Cafe',
        Overall_Rating: 3.1,
        Cuisine: 'Cafe, Sandwich, Pizza, Fast Food, Shake, Coffee, Beverages',
        Rate_for_two: 950,
        City: 'Pune',
        Review: 'Had ordered Pasta. The taste and the presentation of the order were top-notch. Rates are also reasonable considering the taste and portion size.',
    },
    {
        Index: 185,
        Name: 'Crazy Cheesy Cafe',
        Overall_Rating: 3.6,
        Cuisine: 'Cafe, Coffee, Pizza, Italian, Fast Food, Burger, Sandwich, Beverages',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Very good Del Barone pasta!',
    },
    {
        Index: 186,
        Name: 'Journey',
        Overall_Rating: 4,
        Cuisine: 'North Indian, Cafe, Coffee, Chinese, Continental, Oriental, Biryani, Italian',
        Rate_for_two: 1000,
        City: 'Pune',
        Review: 'Curry was great, but the rice served was made in too much oil and oil smelled weird.',
    },
    {
        Index: 187,
        Name: 'Journey',
        Overall_Rating: 4,
        Cuisine: 'North Indian, Cafe, Coffee, Chinese, Continental, Oriental, Biryani, Italian',
        Rate_for_two: 1000,
        City: 'Pune',
        Review: 'I ordered chili garlic noodles, manchurian gravy, chicken garlic. Everything was very tasty. Noodles were very good.',
    },
    {
        Index: 188,
        Name: 'Journey',
        Overall_Rating: 4,
        Cuisine: 'North Indian, Cafe, Coffee, Chinese, Continental, Oriental, Biryani, Italian',
        Rate_for_two: 1000,
        City: 'Pune',
        Review: 'Chicken is not cooked properly, smells very bad.',
    },
    {
        Index: 189,
        Name: 'Kallyfso Cafe',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Fast Food, Burger, Pasta, Sandwich, Pizza, Beverages, Shake',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Food delivered in 50 minutes, which is quite late, as compared to what was promised. French fries are very soggy.',
    },
    {
        Index: 190,
        Name: 'Kallyfso Cafe',
        Overall_Rating: 4,
        Cuisine: 'Cafe, Fast Food, Burger, Pasta, Sandwich, Pizza, Beverages, Shake',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Very delicious food taste. I loved pasta and grilled sandwiches here.',
    },
    {
        Index: 191,
        Name: 'Chai Coffee Charcha',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, North Indian, Chinese, Pizza, Burger, Sandwich',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'I had specifically called the restaurant and asked them not to add corn flour in the veg clear soup as the soup is for the patient. Still, they added the cornflour.',
    },
    {
        Index: 192,
        Name: 'Chai Coffee Charcha',
        Overall_Rating: 4.2,
        Cuisine: 'Cafe, North Indian, Chinese, Pizza, Burger, Sandwich',
        Rate_for_two: 700,
        City: 'Pune',
        Review: 'Nice.',
    },
    {
        Index: 193,
        Name: 'BICE - The Cake Shop & Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Desserts, Shake, Beverages, Sandwich, Fast Food, Bakery',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'The coffee was cold.',
    },
    {
        Index: 194,
        Name: 'BICE - The Cake Shop & Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Desserts, Shake, Beverages, Sandwich, Fast Food, Bakery',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Amazing place to hang out with friends, specialty - Cakes, pastries, Cold coffee, Fries, and other snacks, actually everything. ‚ù§Ô∏è',
    },
    {
        Index: 195,
        Name: 'BICE - The Cake Shop & Cafe',
        Overall_Rating: 3.9,
        Cuisine: 'Cafe, Coffee, Desserts, Shake, Beverages, Sandwich, Fast Food, Bakery',
        Rate_for_two: 500,
        City: 'Pune',
        Review: 'Bice - The cake shop one-stop destination for your customizable cakes. Started by two girls, they have relentlessly worked hard to bring the standards where others can reach only in their dreams. Keep up the good work.',
    },
    {
        Index: 196,
        Name: 'McCafe by McDonald\'s',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Coffee, Shake, Fast Food, Desserts',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'The delivery partner doesn\'t have change he gave me less money and got him a cigarette with my money.',
    },
    {
        Index: 197,
        Name: 'McCafe by McDonald\'s',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Coffee, Shake, Fast Food, Desserts',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'Awesome I\'m lovin it but opens late in the morning not like Mumbai open early at 7 morning Pune is very lazy ppl.',
    },
    {
        Index: 198,
        Name: 'McCafe by McDonald\'s',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Coffee, Shake, Fast Food, Desserts',
        Rate_for_two: 350,
        City: 'Pune',
        Review: 'Paid Rs555 for 2 half cups. Is this a joke? I need my money back.',
    },
    {
        Index: 199,
        Name: 'Cafe Milano',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Italian, Fast Food, Beverages',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Food wasn\'t tasty and they mixed all kinds of pasta when I order Alfredo. Also found hair in the food.',
    },
    {
        Index: 200,
        Name: 'Cafe Milano',
        Overall_Rating: 3.4,
        Cuisine: 'Cafe, Italian, Fast Food, Beverages',
        Rate_for_two: 600,
        City: 'Pune',
        Review: 'Not good service at all.',
    },

];
