export const columns = [
    {
      width: 200,
      label: "Dessert",
      dataKey: "dessert",
    },
    {
      width: 120,
      label: "Calories\u00A0(g)",
      dataKey: "calories",
      numeric: true,
    },
    {
      width: 120,
      label: "Fat\u00A0(g)",
      dataKey: "fat",
      numeric: true,
    },
    {
      width: 120,
      label: "Carbs\u00A0(g)",
      dataKey: "carbs",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "protein",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test2",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein(g)",
      dataKey: "test3",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test4",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test5",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test6",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test7",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test8",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test9",
      numeric: true,
    },
    {
      width: 120,
      label: "Protein\u00A0(g)",
      dataKey: "test10",
      numeric: true,
    },
  ];

export const rows = [
    {
      id: 1,
      dessert:"eqwe1" ,
      calories: 2,
      fat:2,
      carbs:122,
      protein:12,
      test:12,
      test2:12,
      test3:12,
      test4:12,
      test5:12,
      test6:12,
      test7:12,
      test8:12,
      test9:12,
      test10:12,
    },
    {
        id: 1,
        dessert:"eqwe2" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },
      {
        id: 1,
        dessert:"eqwe3" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },
      {
        id: 1,
        dessert:"eqwe4" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },

      {
        id: 1,
        dessert:"eqwe5" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },
      {
        id: 1,
        dessert:"eqwe6" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },
      {
        id: 1,
        dessert:"eqwe7" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },{
        id: 1,
        dessert:"eqwe8" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },{
        id: 1,
        dessert:"eqwe1" ,
        calories: 2,
        fat:2,
        carbs:122,
        protein:12,
        test:12,
        test2:12,
        test3:12,
        test4:12,
        test5:12,
        test6:12,
        test7:12,
        test8:12,
        test9:12,
        test10:12,
      },
      {
          id: 1,
          dessert:"eqwe2" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },
        {
          id: 1,
          dessert:"eqwe3" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },
        {
          id: 1,
          dessert:"eqwe4" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },
  
        {
          id: 1,
          dessert:"eqwe5" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },
        {
          id: 1,
          dessert:"eqwe6" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },
        {
          id: 1,
          dessert:"eqwe7" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },{
          id: 1,
          dessert:"eqwe8" ,
          calories: 2,
          fat:2,
          carbs:122,
          protein:12,
          test:12,
          test2:12,
          test3:12,
          test4:12,
          test5:12,
          test6:12,
          test7:12,
          test8:12,
          test9:12,
          test10:12,
        },{
            id: 1,
            dessert:"eqwe1" ,
            calories: 2,
            fat:2,
            carbs:122,
            protein:12,
            test:12,
            test2:12,
            test3:12,
            test4:12,
            test5:12,
            test6:12,
            test7:12,
            test8:12,
            test9:12,
            test10:12,
          },
          {
              id: 1,
              dessert:"eqwe2" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },
            {
              id: 1,
              dessert:"eqwe3" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },
            {
              id: 1,
              dessert:"eqwe4" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },
      
            {
              id: 1,
              dessert:"eqwe5" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },
            {
              id: 1,
              dessert:"eqwe6" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },
            {
              id: 1,
              dessert:"eqwe7" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },{
              id: 1,
              dessert:"eqwe8" ,
              calories: 2,
              fat:2,
              carbs:122,
              protein:12,
              test:12,
              test2:12,
              test3:12,
              test4:12,
              test5:12,
              test6:12,
              test7:12,
              test8:12,
              test9:12,
              test10:12,
            },{
                id: 1,
                dessert:"eqwe1" ,
                calories: 2,
                fat:2,
                carbs:122,
                protein:12,
                test:12,
                test2:12,
                test3:12,
                test4:12,
                test5:12,
                test6:12,
                test7:12,
                test8:12,
                test9:12,
                test10:12,
              },
              {
                  id: 1,
                  dessert:"eqwe2" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },
                {
                  id: 1,
                  dessert:"eqwe3" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },
                {
                  id: 1,
                  dessert:"eqwe4" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },
          
                {
                  id: 1,
                  dessert:"eqwe5" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },
                {
                  id: 1,
                  dessert:"eqwe6" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },
                {
                  id: 1,
                  dessert:"eqwe7" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },{
                  id: 1,
                  dessert:"eqwe8" ,
                  calories: 2,
                  fat:2,
                  carbs:122,
                  protein:12,
                  test:12,
                  test2:12,
                  test3:12,
                  test4:12,
                  test5:12,
                  test6:12,
                  test7:12,
                  test8:12,
                  test9:12,
                  test10:12,
                },{
                    id: 1,
                    dessert:"eqwe1" ,
                    calories: 2,
                    fat:2,
                    carbs:122,
                    protein:12,
                    test:12,
                    test2:12,
                    test3:12,
                    test4:12,
                    test5:12,
                    test6:12,
                    test7:12,
                    test8:12,
                    test9:12,
                    test10:12,
                  },
                  {
                      id: 1,
                      dessert:"eqwe2" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
                    {
                      id: 1,
                      dessert:"eqwe3" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
                    {
                      id: 1,
                      dessert:"eqwe4" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
              
                    {
                      id: 1,
                      dessert:"eqwe5" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
                    {
                      id: 1,
                      dessert:"eqwe6" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
                    {
                      id: 1,
                      dessert:"eqwe7" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },{
                      id: 1,
                      dessert:"eqwe8" ,
                      calories: 2,
                      fat:2,
                      carbs:122,
                      protein:12,
                      test:12,
                      test2:12,
                      test3:12,
                      test4:12,
                      test5:12,
                      test6:12,
                      test7:12,
                      test8:12,
                      test9:12,
                      test10:12,
                    },
  ];